### ISSUE TITLE
Cannot find TP Keyboard

### ISSUE THREAD

**Issue by thinkycx** [unknownzerx/tpkb#13]
At first, I could use the tpkb very well (2018-2019).
Rencently, I found that the tpkb doesn't work. I don't know why?(Maybe the macOS15? )

I didn't use the Program Karabiner. Is there anyone could help? Thanks.

![image](https://user-images.githubusercontent.com/13138128/79865100-33fecf80-840d-11ea-9111-dcb0b3c97e91.png)

**Comment by ghost** [comment]
Try to grant 'Keyboard Input Monitoring' to terminal app in 'System Preferences' - 'Security & Privacy' - Privacy.

**Comment by thinkycx** [comment]
Thanks for your reply.

I open the setting: 'System Preferences' -> 'Security & Privacy' -> 'Keyboard Input Monitoring'. 
However, there is nothing on the right.
![image](https://user-images.githubusercontent.com/13138128/79946942-868acb00-84a3-11ea-91e0-f153753e2fe7.png)

**Comment by ghost** [comment]
Try stock Terminal.app if you are using others.

**Comment by thinkycx** [comment]
I sorry, what does 'stock Terminal.app' mean?

**Comment by ghost** [comment]
Try /Applications/Utilities/Terminal.app if you are using something like iTerm2.

Or run tpkb from another app #12.

**Comment by thinkycx** [comment]
Thanks for your reply. It works when I run the command in Terminal.app!

However, I wonder whether the command should run with applescript? 
I tried but it still cannot found the device.
The instruction is here. https://technology.siprep.org/running-sudo-commands-in-automator/
```
on run {input, parameters}
	tell application "Terminal"
		do shell script "sudo /Users/***/***/Programs/tpkb/tpkb/tpkb" with administrator privileges
	end tell
end run
```

![image](https://user-images.githubusercontent.com/13138128/79969312-e85b2d00-84c3-11ea-8466-9246c5b24399.png)

**Comment by thinkycx** [comment]
I think the solution to this issue has been found. 
As to the automater script, I think it's not the key point of the problem.
And maybe I will share the script here in future.
