### ISSUE TITLE
feature of changing middle button does not work

### ISSUE THREAD

**Issue by lifei** [unknownzerx/tpkb#3]
I want to disable the click feature and remain the scroll feature.

**Comment by fd1012cd** [comment]
There are two modes. Change

```
    // Middle button
    buf[0] = 0x18;
    buf[1] = 0x09;
    buf[2] = 0x00;
    hid_write(dev, buf, 3);
```

to

```
    // Middle button
    buf[0] = 0x18;
    buf[1] = 0x09;
    buf[2] = 0x01; // <- here
    hid_write(dev, buf, 3);
```

to use another mode ([reference](https://github.com/lentinj/tp-compact-keyboard/blob/master/tp-compact-keyboard)).

However neither modes work as the same as in Windows. I am using SteerMouse 4 for various tweaks, including disabling middle button completely.

**Comment by lifei** [comment]
Thanks
I change to HHKB + TraceBall
