### ISSUE TITLE
Message: "Keyboard not found. Have you run it with 'sudo'?"

### ISSUE THREAD

**Issue by manuel-mauky** [unknownzerx/tpkb#8]
I can't get it to work.

```
> make
gcc -c -o hid.o hid.c
g++ -o tpkb tp.cpp hid.o -framework CoreFoundation -framework IOKit

> sudo ./tpkb
TP Keyboard not found. Have you run it with 'sudo'?
```

Any idea what might be wrong?

**Comment by ghost** [comment]
What keyboard are you using? It supports '0B47189'.

The later model that supports 3 BT connections isn't supported. However, you could change the `product_id` in code and it might work.

**Comment by manuel-mauky** [comment]
Thanks for your response. 

I have the german layout which is "0B47179" according to this [page](https://support.lenovo.com/pe/de/solutions/pd026744).

However, when I look into the system-information app -> Hardware -> Bluetooth -> I see the bluetooth keyboard connected and there is the vendor-id "0x17EF" and product-id "0x6048" which is the same as in the code.

How do I know if I have one of the "later models" that aren't supported? I don't know how many BT connections are supported by my keyboard.

**Comment by Grynn** [comment]
The one with 3 BT connections looks different and is mainly sold in China

https://www.aliexpress.com/item/4X30K12182-New-Original-Lenovo-ThinkPad-Bluetooth-Keyboard-Support-Window-Android-IOS-Multi-Connect-Trackpoint-US-English/32852326699.html


You could try passing in NULL instead of 0 for serial in the call to hid_open? Some docs https://github.com/signal11/hidapi

**Comment by ghost** [comment]
Are you using some app like Karabiner?

**Comment by mgraham** [comment]
Thanks for the hint @ffffwh! 

I had the same problem.  I quit Karabiner-Elements and then ran the tpkb binary and it worked.

**Comment by manuel-mauky** [comment]
Also thanks for the hint in the new version. I was running Karabiner-Elements and after closing it it now works.
